{% set name = "perl-sub-exporter-progressive" %}
{% set version = "0.001013" %}
{% set sha256 = "d535b7954d64da1ac1305b1fadf98202769e3599376854b2ced90c382beac056" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://cpan.metacpan.org/authors/id/F/FR/FREW/Sub-Exporter-Progressive-0.001013.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0

requirements:
  host:
    - perl
    - perl-extutils-makemaker

  run:
    - perl

test:
  imports:
    - Sub::Exporter::Progressive

about:
  home: https://github.com/frioux/Sub-Exporter-Progressive
  license: perl_5
  summary: 'Only use Sub::Exporter if you need it'
