{% set name = "isoncorrect" %}
{% set version = "0.1.3.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/isONcorrect-{{ version }}.tar.gz
  sha256: a05fe9e65392fdefd1bd65ae79317438dee77c36005b2719f9b2c538b4e0e85c

build:
  entry_points:
    - run_isoncorrect = isoncorrect.run_isoncorrect:main
    - isONcorrect = isoncorrect.isONcorrect:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0
  run_exports:
    - {{ pin_subpackage("myrecipe", max_pin="x.x") }}

requirements:
  host:
    - python >=3.7,<4.0
    - setuptools >=61.0
    - pip
  run:
    - python >=3.7,<4.0
    - edlib >=1.1.2
    - numpy >=1.16.2
    - parasail-python >=1.3.4
    - spoa

test:
  imports:
    - isoncorrect
  commands:
    - run_isoncorrect --help
    - isONcorrect --help

about:
  home: https://github.com/ksahlin/isONcorrect
  summary: De novo error-correction of long-read transcriptome reads
  license: GPL-3.0
  license_file: LICENSE.txt

