{% set name = "perl-devel-globaldestruction" %}
{% set version = "0.14" %}
{% set sha256 = "34b8a5f29991311468fe6913cadaba75fd5d2b0b3ee3bb41fe5b53efab9154ab" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://cpan.metacpan.org/authors/id/H/HA/HAARG/Devel-GlobalDestruction-0.14.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0

requirements:
  host:
    - perl
    - perl-sub-exporter-progressive
    - perl-extutils-makemaker

  run:
    - perl
    - perl-sub-exporter-progressive

test:
  imports:
    - Devel::GlobalDestruction

about:
  home: https://metacpan.org/release/Devel-GlobalDestruction
  license: perl_5
  summary: "Provides function returning the equivalent of ${^GLOBAL_PHASE} eq 'DESTRUCT' for older perls."

