{% set name = "perl-module-build-tiny" %}
{% set version = "0.039" %}
{% set sha256 = "7d580ff6ace0cbe555bf36b86dc8ea232581530cbeaaea09bccb57b55797f11c" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://cpan.metacpan.org/authors/id/L/LE/LEONT/Module-Build-Tiny-0.039.tar.gz
  sha256: {{ sha256 }}

build:
  number: 3

requirements:
  host:
    - perl
#    - perl-extutils-install
    - perl-extutils-parsexs
    - perl-extutils-cbuilder
    - perl-xsloader
    - perl-file-path
    - perl-data-dumper
    - perl-lib
    - perl-json-pp
    - perl-extutils-config
    - perl-exporter
    - perl-getopt-long
    - perl-carp
    - perl-extutils-installpaths
    - perl-extutils-helpers
    - perl-cpan-meta
    - perl-file-temp

  run:
    - perl
    - perl-file-path
 #   - perl-extutils-install
    - perl-json-pp
    - perl-extutils-config
    - perl-exporter
    - perl-getopt-long
    - perl-extutils-installpaths
    - perl-extutils-helpers
    - perl-extutils-parsexs
    - perl-cpan-meta
    - perl-extutils-cbuilder

test:
  imports:
    - Module::Build::Tiny

about:
  home: http://metacpan.org/pod/Module::Build::Tiny
  license: perl_5
  summary: 'A tiny replacement for Module::Build'
